Individual Project 2, Liezel Dela Cruz, DS-160-01

# 

a.	Create a 2-by-2 NumPy array with elements 10,20,30,40 in it. Then use broadcasting to perform each of these operations:

In [15]:
import numpy as np
x=np.arange(10,50,10)
x.resize(2,2)
print(x)

[[10 20]
 [30 40]]


(i) Square every element of the array.

In [16]:
square=np.square(x)
print(square)

[[ 100  400]
 [ 900 1600]]


(ii) Add 100 to every element of the array.

In [17]:
add=x+1
print (add)

[[11 21]
 [31 41]]


(iii) Multiply every element of the array by 5.

In [18]:
multiply=x*5
print(multiply)

[[ 50 100]
 [150 200]]


(iv) Calculate the square root of each element in the array.

In [19]:
root=np.sqrt(x)
print(root)

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


# 

b.	Create a 3-by-3 array containing integers from 3 to 27 in multiples of 3.  Create a second 3-by-3 array with 9 elements evenly spaced between 10 and 20.  Multiply these arrays together and display the output.

In [20]:
y=np.arange(3,30,3).reshape(3,3)
print(y)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [21]:
z=np.linspace(10,20,9).reshape(3,3)
print(z)

[[10.   11.25 12.5 ]
 [13.75 15.   16.25]
 [17.5  18.75 20.  ]]


In [22]:
yz=y*z
print(yz)

[[ 30.   67.5 112.5]
 [165.  225.  292.5]
 [367.5 450.  540. ]]


# 

c.	Attached to the assignment are five .npy files that contain five values each. Read these files in and stack them into a unified dataset.  This would be a 5-by-5 NumPy array.  Then calculate the mean of each column of data. Let Python do all of the heavy liftings! Don’t forget, you need to put the .npy files in the same directory as your script.

In [23]:
data1 = np.load("process1.npy" , mmap_mode = 'r')
data2 = np.load("process2.npy", mmap_mode = 'r')
data3 = np.load("process3.npy" , mmap_mode = 'r')
data4 = np.load("process4.npy", mmap_mode = 'r')
data5 = np.load("process5.npy" , mmap_mode = 'r')

data = np.array([data1,data2,data3,data4,data5]).reshape(5,5)
print(data)

[[52 12 81  0 58]
 [96  4 61 16 43]
 [38 96 45 17 58]
 [97 21 22 25  6]
 [77  6 19  2 74]]


In [24]:
mean1 = np.mean(data[:,0])
print("Column 1 Mean: ", mean1)

mean2 = np.mean(data[:,1])
print("Column 2 Mean: ", mean2)

mean3 = np.mean(data[:,2])
print("Column 3 Mean: ", mean3)

mean4 = np.mean(data[:,3])
print("Column 4 Mean: ", mean4)

mean5 = np.mean(data[:,4])
print("Column 5 Mean: ", mean5)

Column 1 Mean:  72.0
Column 2 Mean:  27.8
Column 3 Mean:  45.6
Column 4 Mean:  12.0
Column 5 Mean:  47.8
